### PR TITLE
Drop StrideArrays.jl, move to UnsafeArrays.jl

### LINKED ISSUE #34: MethodErrors caused by StrideArrays.jl overrides
MWE:

In a fresh REPL:

```julia
julia> using Bumper: @no_escape, @alloc

julia> using Random: randn!

julia> T = ComplexF32
ComplexF32 (alias for Complex{Float32})

julia> @no_escape begin
           ar = @alloc(T, 100)
           randn!(ar)
           @. ar = cos(ar)
           sum(ar)
       end
109.13606f0 + 4.8591895f0im
```

However, if I import `StrideArrays`, I get an error:

```julia
julia> using Bumper: @no_escape, @alloc

julia> using StrideArrays

julia> using Random: randn!

julia> T = ComplexF32
ComplexF32 (alias for Complex{Float32})

julia> @no_escape begin
           ar = @alloc(T, 100)
           randn!(ar)
           @. ar = cos(ar)
           sum(ar)
       end
ERROR: MethodError: no method matching vmaterialize!(::PtrArray{…}, ::Base.Broadcast.Broadcasted{…}, ::Val{…}, ::Val{…}, ::Val{…})

Closest candidates are:
  vmaterialize!(::Any, ::Any, ::Val{Mod}, ::Val{UNROLL}) where {Mod, UNROLL}
   @ LoopVectorization ~/.julia/packages/LoopVectorization/7gWfp/src/broadcast.jl:753
  vmaterialize!(::Union{LinearAlgebra.Adjoint{T, A}, LinearAlgebra.Transpose{T, A}}, ::BC, ::Val{Mod}, ::Val{UNROLL}, ::Val{dontbc}) where {T<:Union{Bool, Float16, Float32, Float64, Int16, Int32, Int64, Int8, UInt16, UInt32, UInt64, UInt8, SIMDTypes.Bit}, N, A<:AbstractArray{T, N}, BC<:Union{Base.Broadcast.Broadcasted, LoopVectorization.Product}, Mod, UNROLL, dontbc}
   @ LoopVectorization ~/.julia/packages/LoopVectorization/7gWfp/src/broadcast.jl:682
  vmaterialize!(::AbstractArray{T, N}, ::BC, ::Val{Mod}, ::Val{UNROLL}, ::Val{dontbc}) where {T<:Union{Bool, Float16, Float32, Float64, Int16, Int32, Int64, Int8, UInt16, UInt32, UInt64, UInt8, SIMDTypes.Bit}, N, BC<:Union{Base.Broadcast.Broadcasted, LoopVectorization.Product}, Mod, UNROLL, dontbc}
   @ LoopVectorization ~/.julia/packages/LoopVectorization/7gWfp/src/broadcast.jl:673
  ...

Stacktrace:
 [1] vmaterialize!
   @ LoopVectorization ~/.julia/packages/LoopVectorization/7gWfp/src/broadcast.jl:759 [inlined]
 [2] _materialize!
   @ StrideArrays ~/.julia/packages/StrideArrays/PeLtr/src/broadcast.jl:181 [inlined]
 [3] materialize!(dest::PtrArray{…}, bc::Base.Broadcast.Broadcasted{…})
   @ StrideArrays ~/.julia/packages/StrideArrays/PeLtr/src/broadcast.jl:188
 [4] macro expansion
   @ REPL[5]:4 [inlined]
 [5] macro expansion
   @ ~/.julia/packages/Bumper/eoK0g/src/internals.jl:74 [inlined]
 [6] top-level scope
   @ REPL[5]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

I think maybe a fallback methods should be used if it doesn't exist?

### PR DESCRIPTION
**Pull request by MasonProtter**
closes #34 sorry @milescranmer it took me so long to get around to this. None of the options I looked at were as fast as StrideArrays.jl, but eventually I decided it didn't really matter because they were at least faster than `Array`.

I had hoped to find the time to figure out how to make up the remainder of the performance difference, but I never got around to it, so now I'm thinking lets just go forward with UnsafeArrays.jl

Let me know what you think.

### CODE REVIEW

**Comment by MilesCranmer** [comment]
Sounds good! :+1:

**Comment by MasonProtter** [comment]
Okay I'm gonna merge this now, and it'll be available as version 0.7 (technically breaking because the types returned from `@alloc`  have changed). 

This also fixes #39

**Comment by bvdmitri** [comment]
I guess that could have broken `MallocSlabBuffer` from https://github.com/brenhinkeller/StaticTools.jl? I cannot access it anymore on the new version...
```julia
(jl_7uvlgW) pkg> st
Status `/private/var/folders/x3/rqw10ky529915v7_l4t7vz0m0000gn/T/jl_7uvlgW/Project.toml`
  [8ce10254] Bumper v0.7.0
⌃ [86c06d3c] StaticTools v0.8.8

julia> StaticTools.MallocSlabBuffer()
ERROR: UndefVarError: `MallocSlabBuffer` not defined
```
previously
```julia
(jl_R3t6Vx) pkg> st
Status `/private/var/folders/x3/rqw10ky529915v7_l4t7vz0m0000gn/T/jl_R3t6Vx/Project.toml`
⌅ [8ce10254] Bumper v0.6.0
  [86c06d3c] StaticTools v0.8.10

julia> using StaticTools, Bumper

julia> StaticTools.MallocSlabBuffer()
MallocSlabBuffer(Ptr{StaticTools.MallocSlabBufferData} @0x0000600002a22710)
```
I guess the new version prevents `StaticTools` to install the latest available version?

**Comment by bvdmitri** [comment]
Ah, probably needs the Project.toml update [here](https://github.com/brenhinkeller/StaticTools.jl/blob/f3f36597eb66cdbd44bd30c46ddb2321b6b8772c/Project.toml#L16)

**Pull request merged**
